// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: collection.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const addPlaceToCollection = `-- name: AddPlaceToCollection :exec
INSERT INTO collection_place (collection_id, place_id)
VALUES ($1, $2)
ON CONFLICT (collection_id, place_id) DO NOTHING
`

type AddPlaceToCollectionParams struct {
	CollectionID uuid.UUID
	PlaceID      uuid.UUID
}

func (q *Queries) AddPlaceToCollection(ctx context.Context, arg AddPlaceToCollectionParams) error {
	_, err := q.db.ExecContext(ctx, addPlaceToCollection, arg.CollectionID, arg.PlaceID)
	return err
}

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (user_id, name)
VALUES ($1, $2)
RETURNING id, user_id, name, created_at, updated_at
`

type CreateCollectionParams struct {
	UserID uuid.UUID
	Name   string
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.db.QueryRowContext(ctx, createCollection, arg.UserID, arg.Name)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCollection = `-- name: DeleteCollection :exec
DELETE FROM collections
WHERE id = $1
`

func (q *Queries) DeleteCollection(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCollection, id)
	return err
}

const getCollection = `-- name: GetCollection :one
SELECT id, user_id, name, created_at, updated_at
FROM collections
WHERE id = $1
`

func (q *Queries) GetCollection(ctx context.Context, id uuid.UUID) (Collection, error) {
	row := q.db.QueryRowContext(ctx, getCollection, id)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCollectionItemsByPlaceIDs = `-- name: ListCollectionItemsByPlaceIDs :many
SELECT cp.place_id, c.id AS collection_id, c.name
FROM collection_place cp
INNER JOIN collections c ON c.id = cp.collection_id
WHERE c.user_id = $1::uuid AND cp.place_id = ANY($2::uuid[])
ORDER BY cp.place_id, c.name
`

type ListCollectionItemsByPlaceIDsParams struct {
	UserID   uuid.UUID
	PlaceIds []uuid.UUID
}

type ListCollectionItemsByPlaceIDsRow struct {
	PlaceID      uuid.UUID
	CollectionID uuid.UUID
	Name         string
}

func (q *Queries) ListCollectionItemsByPlaceIDs(ctx context.Context, arg ListCollectionItemsByPlaceIDsParams) ([]ListCollectionItemsByPlaceIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCollectionItemsByPlaceIDs, arg.UserID, pq.Array(arg.PlaceIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCollectionItemsByPlaceIDsRow
	for rows.Next() {
		var i ListCollectionItemsByPlaceIDsRow
		if err := rows.Scan(&i.PlaceID, &i.CollectionID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionsByUser = `-- name: ListCollectionsByUser :many
SELECT id, user_id, name, created_at, updated_at
FROM collections
WHERE user_id = $1
ORDER BY name ASC
`

func (q *Queries) ListCollectionsByUser(ctx context.Context, userID uuid.UUID) ([]Collection, error) {
	rows, err := q.db.QueryContext(ctx, listCollectionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collection
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionsByUserWithPlaceCount = `-- name: ListCollectionsByUserWithPlaceCount :many
SELECT c.id, c.name, COUNT(cp.place_id)::int AS place_count
FROM collections c
LEFT JOIN collection_place cp ON cp.collection_id = c.id
WHERE c.user_id = $1
GROUP BY c.id, c.name
ORDER BY c.name ASC
`

type ListCollectionsByUserWithPlaceCountRow struct {
	ID         uuid.UUID
	Name       string
	PlaceCount int32
}

func (q *Queries) ListCollectionsByUserWithPlaceCount(ctx context.Context, userID uuid.UUID) ([]ListCollectionsByUserWithPlaceCountRow, error) {
	rows, err := q.db.QueryContext(ctx, listCollectionsByUserWithPlaceCount, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCollectionsByUserWithPlaceCountRow
	for rows.Next() {
		var i ListCollectionsByUserWithPlaceCountRow
		if err := rows.Scan(&i.ID, &i.Name, &i.PlaceCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCollectionsForPlace = `-- name: ListCollectionsForPlace :many
SELECT c.id, c.user_id, c.name, c.created_at, c.updated_at
FROM collections c
INNER JOIN collection_place cp ON cp.collection_id = c.id
WHERE c.user_id = $1 AND cp.place_id = $2
ORDER BY c.name ASC
`

type ListCollectionsForPlaceParams struct {
	UserID  uuid.UUID
	PlaceID uuid.UUID
}

func (q *Queries) ListCollectionsForPlace(ctx context.Context, arg ListCollectionsForPlaceParams) ([]Collection, error) {
	rows, err := q.db.QueryContext(ctx, listCollectionsForPlace, arg.UserID, arg.PlaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Collection
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlacesInCollection = `-- name: ListPlacesInCollection :many
SELECT p.id, p.name
FROM place p
INNER JOIN collection_place cp ON cp.place_id = p.id
WHERE cp.collection_id = $1
ORDER BY p.name ASC
`

type ListPlacesInCollectionRow struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) ListPlacesInCollection(ctx context.Context, collectionID uuid.UUID) ([]ListPlacesInCollectionRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlacesInCollection, collectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlacesInCollectionRow
	for rows.Next() {
		var i ListPlacesInCollectionRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePlaceFromCollection = `-- name: RemovePlaceFromCollection :exec
DELETE FROM collection_place
WHERE collection_id = $1 AND place_id = $2
`

type RemovePlaceFromCollectionParams struct {
	CollectionID uuid.UUID
	PlaceID      uuid.UUID
}

func (q *Queries) RemovePlaceFromCollection(ctx context.Context, arg RemovePlaceFromCollectionParams) error {
	_, err := q.db.ExecContext(ctx, removePlaceFromCollection, arg.CollectionID, arg.PlaceID)
	return err
}
