// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guide.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const addPlaceToGuideStep = `-- name: AddPlaceToGuideStep :exec
INSERT INTO guide_step_place (guide_step_id, place_id, position, option_note)
VALUES ($1::uuid, $2::uuid, $3::int, $4::text)
ON CONFLICT (guide_step_id, place_id) DO UPDATE SET
    option_note = EXCLUDED.option_note
`

type AddPlaceToGuideStepParams struct {
	GuideStepID uuid.UUID
	PlaceID     uuid.UUID
	Position    int32
	OptionNote  string
}

func (q *Queries) AddPlaceToGuideStep(ctx context.Context, arg AddPlaceToGuideStepParams) error {
	_, err := q.db.ExecContext(ctx, addPlaceToGuideStep,
		arg.GuideStepID,
		arg.PlaceID,
		arg.Position,
		arg.OptionNote,
	)
	return err
}

const countPlaceInGuide = `-- name: CountPlaceInGuide :one
SELECT COUNT(*)::int
FROM guide_step_place gsp
INNER JOIN guide_step gs ON gs.id = gsp.guide_step_id
WHERE gs.guide_id = $1::uuid AND gsp.place_id = $2::uuid
`

type CountPlaceInGuideParams struct {
	GuideID uuid.UUID
	PlaceID uuid.UUID
}

func (q *Queries) CountPlaceInGuide(ctx context.Context, arg CountPlaceInGuideParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, countPlaceInGuide, arg.GuideID, arg.PlaceID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countPlacesInGuideStep = `-- name: CountPlacesInGuideStep :one
SELECT COUNT(*)::int
FROM guide_step_place
WHERE guide_step_id = $1::uuid
`

func (q *Queries) CountPlacesInGuideStep(ctx context.Context, guideStepID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, countPlacesInGuideStep, guideStepID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createGuide = `-- name: CreateGuide :one
INSERT INTO guide (user_id, title, blurb, cover_url, tags)
VALUES (
    $1::uuid,
    $2::text,
    $3::text,
    $4::text,
    COALESCE($5::jsonb, '[]'::jsonb)
)
RETURNING id, user_id, title, blurb, cover_url, tags, created_at, updated_at
`

type CreateGuideParams struct {
	UserID   uuid.UUID
	Title    string
	Blurb    string
	CoverUrl string
	Tags     json.RawMessage
}

func (q *Queries) CreateGuide(ctx context.Context, arg CreateGuideParams) (Guide, error) {
	row := q.db.QueryRowContext(ctx, createGuide,
		arg.UserID,
		arg.Title,
		arg.Blurb,
		arg.CoverUrl,
		arg.Tags,
	)
	var i Guide
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Blurb,
		&i.CoverUrl,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGuideStep = `-- name: CreateGuideStep :one
INSERT INTO guide_step (guide_id, position, step_title, step_note)
VALUES ($1::uuid, $2::int, $3::text, $4::text)
RETURNING id, guide_id, position, step_title, step_note
`

type CreateGuideStepParams struct {
	GuideID   uuid.UUID
	Position  int32
	StepTitle string
	StepNote  string
}

func (q *Queries) CreateGuideStep(ctx context.Context, arg CreateGuideStepParams) (GuideStep, error) {
	row := q.db.QueryRowContext(ctx, createGuideStep,
		arg.GuideID,
		arg.Position,
		arg.StepTitle,
		arg.StepNote,
	)
	var i GuideStep
	err := row.Scan(
		&i.ID,
		&i.GuideID,
		&i.Position,
		&i.StepTitle,
		&i.StepNote,
	)
	return i, err
}

const deleteEmptyStepsInGuide = `-- name: DeleteEmptyStepsInGuide :exec
DELETE FROM guide_step AS gs
WHERE gs.guide_id = $1::uuid
  AND NOT EXISTS (
    SELECT 1 FROM guide_step_place gsp WHERE gsp.guide_step_id = gs.id
  )
`

func (q *Queries) DeleteEmptyStepsInGuide(ctx context.Context, guideID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteEmptyStepsInGuide, guideID)
	return err
}

const deleteGuide = `-- name: DeleteGuide :exec
DELETE FROM guide
WHERE id = $1::uuid AND user_id = $2::uuid
`

type DeleteGuideParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteGuide(ctx context.Context, arg DeleteGuideParams) error {
	_, err := q.db.ExecContext(ctx, deleteGuide, arg.ID, arg.UserID)
	return err
}

const deleteGuideStep = `-- name: DeleteGuideStep :exec
DELETE FROM guide_step
WHERE id = $1::uuid AND guide_id = $2::uuid
`

type DeleteGuideStepParams struct {
	ID      uuid.UUID
	GuideID uuid.UUID
}

func (q *Queries) DeleteGuideStep(ctx context.Context, arg DeleteGuideStepParams) error {
	_, err := q.db.ExecContext(ctx, deleteGuideStep, arg.ID, arg.GuideID)
	return err
}

const getGuide = `-- name: GetGuide :one
SELECT id, user_id, title, blurb, cover_url, tags, created_at, updated_at
FROM guide
WHERE id = $1::uuid AND user_id = $2::uuid
`

type GetGuideParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetGuide(ctx context.Context, arg GetGuideParams) (Guide, error) {
	row := q.db.QueryRowContext(ctx, getGuide, arg.ID, arg.UserID)
	var i Guide
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Blurb,
		&i.CoverUrl,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGuideItemsByPlaceIDs = `-- name: ListGuideItemsByPlaceIDs :many
SELECT
    gsp.place_id,
    g.id AS guide_id,
    g.title AS guide_name
FROM guide_step_place gsp
INNER JOIN guide_step gs ON gs.id = gsp.guide_step_id
INNER JOIN guide g ON g.id = gs.guide_id
WHERE g.user_id = $1::uuid
  AND gsp.place_id = ANY($2::uuid[])
ORDER BY gsp.place_id, g.title
`

type ListGuideItemsByPlaceIDsParams struct {
	UserID   uuid.UUID
	PlaceIds []uuid.UUID
}

type ListGuideItemsByPlaceIDsRow struct {
	PlaceID   uuid.UUID
	GuideID   uuid.UUID
	GuideName string
}

func (q *Queries) ListGuideItemsByPlaceIDs(ctx context.Context, arg ListGuideItemsByPlaceIDsParams) ([]ListGuideItemsByPlaceIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, listGuideItemsByPlaceIDs, arg.UserID, pq.Array(arg.PlaceIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGuideItemsByPlaceIDsRow
	for rows.Next() {
		var i ListGuideItemsByPlaceIDsRow
		if err := rows.Scan(&i.PlaceID, &i.GuideID, &i.GuideName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuideStepPlacesWithPlace = `-- name: ListGuideStepPlacesWithPlace :many
SELECT
    gsp.guide_step_id,
    gsp.place_id,
    gsp.position,
    gsp.option_note,
    p.name AS place_name,
    ST_Y(p.location::geometry)::float AS latitude,
    ST_X(p.location::geometry)::float AS longitude,
    COALESCE(
        (
            SELECT pi.url
            FROM place_image pi
            WHERE pi.place_id = gsp.place_id
            ORDER BY pi.is_primary DESC NULLS LAST, pi.created_at ASC
            LIMIT 1
        ),
        ''
    )::text AS primary_image_url,
    COALESCE(
        (
            SELECT json_agg(pi.url ORDER BY pi.is_primary DESC NULLS LAST, pi.created_at ASC)
            FROM place_image pi
            WHERE pi.place_id = gsp.place_id
        )::text,
        '[]'::text
    ) AS image_urls,
    COALESCE(p.tags, '[]'::jsonb) AS tags,
    (SELECT COUNT(*)::int FROM place_image pi WHERE pi.place_id = gsp.place_id) AS photo_count,
    (SELECT COUNT(*)::int FROM user_place_interactions WHERE place_id = gsp.place_id AND liked = true) AS like_count,
    p.opening_hours
FROM guide_step_place gsp
INNER JOIN place p ON p.id = gsp.place_id
WHERE gsp.guide_step_id = ANY($1::uuid[])
ORDER BY gsp.guide_step_id, gsp.position ASC
`

type ListGuideStepPlacesWithPlaceRow struct {
	GuideStepID     uuid.UUID
	PlaceID         uuid.UUID
	Position        int32
	OptionNote      sql.NullString
	PlaceName       string
	Latitude        float64
	Longitude       float64
	PrimaryImageUrl string
	ImageUrls       interface{}
	Tags            pqtype.NullRawMessage
	PhotoCount      int32
	LikeCount       int32
	OpeningHours    sql.NullString
}

func (q *Queries) ListGuideStepPlacesWithPlace(ctx context.Context, guideStepIds []uuid.UUID) ([]ListGuideStepPlacesWithPlaceRow, error) {
	rows, err := q.db.QueryContext(ctx, listGuideStepPlacesWithPlace, pq.Array(guideStepIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGuideStepPlacesWithPlaceRow
	for rows.Next() {
		var i ListGuideStepPlacesWithPlaceRow
		if err := rows.Scan(
			&i.GuideStepID,
			&i.PlaceID,
			&i.Position,
			&i.OptionNote,
			&i.PlaceName,
			&i.Latitude,
			&i.Longitude,
			&i.PrimaryImageUrl,
			&i.ImageUrls,
			&i.Tags,
			&i.PhotoCount,
			&i.LikeCount,
			&i.OpeningHours,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuideStepsByGuideID = `-- name: ListGuideStepsByGuideID :many
SELECT id, guide_id, position, step_title, step_note
FROM guide_step
WHERE guide_id = $1::uuid
ORDER BY position ASC
`

func (q *Queries) ListGuideStepsByGuideID(ctx context.Context, guideID uuid.UUID) ([]GuideStep, error) {
	rows, err := q.db.QueryContext(ctx, listGuideStepsByGuideID, guideID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GuideStep
	for rows.Next() {
		var i GuideStep
		if err := rows.Scan(
			&i.ID,
			&i.GuideID,
			&i.Position,
			&i.StepTitle,
			&i.StepNote,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGuidesByUserWithCounts = `-- name: ListGuidesByUserWithCounts :many
SELECT
    g.id,
    g.title,
    (SELECT COUNT(*)::int FROM guide_step gs WHERE gs.guide_id = g.id) AS step_count,
    (SELECT COUNT(*)::int
     FROM guide_step gs
     INNER JOIN guide_step_place gsp ON gsp.guide_step_id = gs.id
     WHERE gs.guide_id = g.id) AS place_count
FROM guide g
WHERE g.user_id = $1::uuid
ORDER BY g.updated_at DESC, g.title ASC
`

type ListGuidesByUserWithCountsRow struct {
	ID         uuid.UUID
	Title      string
	StepCount  int32
	PlaceCount int32
}

func (q *Queries) ListGuidesByUserWithCounts(ctx context.Context, userID uuid.UUID) ([]ListGuidesByUserWithCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listGuidesByUserWithCounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGuidesByUserWithCountsRow
	for rows.Next() {
		var i ListGuidesByUserWithCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.StepCount,
			&i.PlaceCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxGuideStepPosition = `-- name: MaxGuideStepPosition :one
SELECT COALESCE(MAX(position), -1)::int AS max_pos
FROM guide_step
WHERE guide_id = $1::uuid
`

func (q *Queries) MaxGuideStepPosition(ctx context.Context, guideID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, maxGuideStepPosition, guideID)
	var max_pos int32
	err := row.Scan(&max_pos)
	return max_pos, err
}

const maxPlacePositionInStep = `-- name: MaxPlacePositionInStep :one
SELECT COALESCE(MAX(position), -1)::int AS max_pos
FROM guide_step_place
WHERE guide_step_id = $1::uuid
`

func (q *Queries) MaxPlacePositionInStep(ctx context.Context, guideStepID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, maxPlacePositionInStep, guideStepID)
	var max_pos int32
	err := row.Scan(&max_pos)
	return max_pos, err
}

const removePlaceFromGuideEverywhere = `-- name: RemovePlaceFromGuideEverywhere :exec
DELETE FROM guide_step_place AS gsp
USING guide_step AS gs
WHERE gsp.guide_step_id = gs.id
  AND gs.guide_id = $1::uuid
  AND gsp.place_id = $2::uuid
`

type RemovePlaceFromGuideEverywhereParams struct {
	GuideID uuid.UUID
	PlaceID uuid.UUID
}

func (q *Queries) RemovePlaceFromGuideEverywhere(ctx context.Context, arg RemovePlaceFromGuideEverywhereParams) error {
	_, err := q.db.ExecContext(ctx, removePlaceFromGuideEverywhere, arg.GuideID, arg.PlaceID)
	return err
}

const removePlaceFromGuideStep = `-- name: RemovePlaceFromGuideStep :exec
DELETE FROM guide_step_place
WHERE guide_step_id = $1::uuid AND place_id = $2::uuid
`

type RemovePlaceFromGuideStepParams struct {
	GuideStepID uuid.UUID
	PlaceID     uuid.UUID
}

func (q *Queries) RemovePlaceFromGuideStep(ctx context.Context, arg RemovePlaceFromGuideStepParams) error {
	_, err := q.db.ExecContext(ctx, removePlaceFromGuideStep, arg.GuideStepID, arg.PlaceID)
	return err
}

const updateGuide = `-- name: UpdateGuide :one
UPDATE guide
SET
    title = $1::text,
    blurb = $2::text,
    cover_url = $3::text,
    tags = COALESCE($4::jsonb, tags),
    updated_at = NOW()
WHERE id = $5::uuid AND user_id = $6::uuid
RETURNING id, user_id, title, blurb, cover_url, tags, created_at, updated_at
`

type UpdateGuideParams struct {
	Title    string
	Blurb    string
	CoverUrl string
	Tags     json.RawMessage
	ID       uuid.UUID
	UserID   uuid.UUID
}

func (q *Queries) UpdateGuide(ctx context.Context, arg UpdateGuideParams) (Guide, error) {
	row := q.db.QueryRowContext(ctx, updateGuide,
		arg.Title,
		arg.Blurb,
		arg.CoverUrl,
		arg.Tags,
		arg.ID,
		arg.UserID,
	)
	var i Guide
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Blurb,
		&i.CoverUrl,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGuideStepContent = `-- name: UpdateGuideStepContent :exec
UPDATE guide_step
SET step_title = $1::text,
    step_note = $2::text
WHERE id = $3::uuid AND guide_id = $4::uuid
`

type UpdateGuideStepContentParams struct {
	StepTitle string
	StepNote  string
	StepID    uuid.UUID
	GuideID   uuid.UUID
}

func (q *Queries) UpdateGuideStepContent(ctx context.Context, arg UpdateGuideStepContentParams) error {
	_, err := q.db.ExecContext(ctx, updateGuideStepContent,
		arg.StepTitle,
		arg.StepNote,
		arg.StepID,
		arg.GuideID,
	)
	return err
}

const updateGuideStepPlaceOptionNote = `-- name: UpdateGuideStepPlaceOptionNote :exec
UPDATE guide_step_place
SET option_note = $1::text
WHERE guide_step_id = $2::uuid AND place_id = $3::uuid
`

type UpdateGuideStepPlaceOptionNoteParams struct {
	OptionNote  string
	GuideStepID uuid.UUID
	PlaceID     uuid.UUID
}

func (q *Queries) UpdateGuideStepPlaceOptionNote(ctx context.Context, arg UpdateGuideStepPlaceOptionNoteParams) error {
	_, err := q.db.ExecContext(ctx, updateGuideStepPlaceOptionNote, arg.OptionNote, arg.GuideStepID, arg.PlaceID)
	return err
}
