// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Collection struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type CollectionPlace struct {
	CollectionID uuid.UUID
	PlaceID      uuid.UUID
	CreatedAt    time.Time
}

type Place struct {
	ID           uuid.UUID
	Name         string
	Description  sql.NullString
	Category     string
	Location     interface{}
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Tags         pqtype.NullRawMessage
	OpeningHours sql.NullString
	WikidataID   sql.NullString
}

type PlaceImage struct {
	ID          uuid.UUID
	PlaceID     uuid.UUID
	Url         string
	Description sql.NullString
	IsPrimary   sql.NullBool
	CreatedAt   time.Time
}

type SearchedLocation struct {
	ID        uuid.UUID
	Lat       float64
	Long      float64
	RadiusKm  float64
	CreatedAt time.Time
}

type User struct {
	ID        uuid.UUID
	GoogleID  string
	Name      sql.NullString
	Email     sql.NullString
	Picture   sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UserPlaceInteraction struct {
	UserID            uuid.UUID
	PlaceID           uuid.UUID
	Liked             bool
	Hidden            bool
	LastInteractionAt sql.NullTime
	CreatedAt         time.Time
	UpdatedAt         time.Time
}
