// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Place struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	Category    string
	Location    interface{}
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
