// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Guide struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Title     string
	Blurb     sql.NullString
	CoverUrl  sql.NullString
	Tags      json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

type GuideStep struct {
	ID        uuid.UUID
	GuideID   uuid.UUID
	Position  int32
	StepTitle string
	StepNote  sql.NullString
}

type GuideStepPlace struct {
	GuideStepID uuid.UUID
	PlaceID     uuid.UUID
	Position    int32
	OptionNote  sql.NullString
}

type Place struct {
	ID           uuid.UUID
	Name         string
	Description  sql.NullString
	Category     string
	Location     interface{}
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Tags         pqtype.NullRawMessage
	OpeningHours sql.NullString
	WikidataID   sql.NullString
}

type PlaceImage struct {
	ID          uuid.UUID
	PlaceID     uuid.UUID
	Url         string
	Description sql.NullString
	IsPrimary   sql.NullBool
	CreatedAt   time.Time
}

type SearchedLocation struct {
	ID        uuid.UUID
	Lat       float64
	Long      float64
	RadiusKm  float64
	CreatedAt time.Time
}

type User struct {
	ID        uuid.UUID
	GoogleID  string
	Name      sql.NullString
	Email     sql.NullString
	Picture   sql.NullString
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UserPlaceInteraction struct {
	UserID            uuid.UUID
	PlaceID           uuid.UUID
	Liked             bool
	Hidden            bool
	LastInteractionAt sql.NullTime
	CreatedAt         time.Time
	UpdatedAt         time.Time
}
