// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: place.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const addPlaceImagesBatch = `-- name: AddPlaceImagesBatch :exec
INSERT INTO place_image (place_id, url, description, is_primary)
SELECT
    unnest($1::uuid[]),
    unnest($2::text[]),
    unnest($3::text[]),
    unnest($4::boolean[])
`

type AddPlaceImagesBatchParams struct {
	PlaceIds     []uuid.UUID
	Urls         []string
	Descriptions []string
	IsPrimaries  []bool
}

func (q *Queries) AddPlaceImagesBatch(ctx context.Context, arg AddPlaceImagesBatchParams) error {
	_, err := q.db.ExecContext(ctx, addPlaceImagesBatch,
		pq.Array(arg.PlaceIds),
		pq.Array(arg.Urls),
		pq.Array(arg.Descriptions),
		pq.Array(arg.IsPrimaries),
	)
	return err
}

const createPlacesBatch = `-- name: CreatePlacesBatch :many
INSERT INTO place (name, description, category, location)
SELECT
    unnest($1::text[]),
    unnest($2::text[]),
    unnest($3::text[]),
    ST_SetSRID(ST_MakePoint(unnest($4::float8[]), unnest($5::float8[])), 4326)
RETURNING id
`

type CreatePlacesBatchParams struct {
	Names        []string
	Descriptions []string
	Categories   []string
	Longs        []float64
	Lats         []float64
}

func (q *Queries) CreatePlacesBatch(ctx context.Context, arg CreatePlacesBatchParams) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, createPlacesBatch,
		pq.Array(arg.Names),
		pq.Array(arg.Descriptions),
		pq.Array(arg.Categories),
		pq.Array(arg.Longs),
		pq.Array(arg.Lats),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaceImagesByPlaceIDs = `-- name: ListPlaceImagesByPlaceIDs :many
SELECT place_id, url, description, is_primary
FROM place_image
WHERE place_id = ANY($1::uuid[])
ORDER BY place_id, is_primary DESC
`

type ListPlaceImagesByPlaceIDsRow struct {
	PlaceID     uuid.UUID
	Url         string
	Description sql.NullString
	IsPrimary   sql.NullBool
}

func (q *Queries) ListPlaceImagesByPlaceIDs(ctx context.Context, placeIds []uuid.UUID) ([]ListPlaceImagesByPlaceIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlaceImagesByPlaceIDs, pq.Array(placeIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlaceImagesByPlaceIDsRow
	for rows.Next() {
		var i ListPlaceImagesByPlaceIDsRow
		if err := rows.Scan(
			&i.PlaceID,
			&i.Url,
			&i.Description,
			&i.IsPrimary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaces = `-- name: ListPlaces :many
SELECT
    p.id,
    p.name,
    p.category,
    p.description,
    ST_Y(p.location::geometry)::float AS latitude,
    ST_X(p.location::geometry)::float AS longitude,
    COALESCE(upi.liked, FALSE) AS liked
FROM place p
LEFT JOIN user_place_interactions upi ON p.id = upi.place_id AND upi.user_id = $3::uuid
WHERE ST_DWithin(
    p.location::geography,
    ST_SetSRID(ST_MakePoint($4::float, $5::float), 4326)::geography,
    $6::float
) AND COALESCE(upi.hidden, FALSE) = FALSE
ORDER BY ST_Distance(
    p.location::geography,
    ST_SetSRID(ST_MakePoint($4::float, $5::float), 4326)::geography
) ASC
LIMIT $1 OFFSET $2
`

type ListPlacesParams struct {
	Limit        int32
	Offset       int32
	UserID       uuid.UUID
	Lon          float64
	Lat          float64
	RadiusMeters float64
}

type ListPlacesRow struct {
	ID          uuid.UUID
	Name        string
	Category    string
	Description sql.NullString
	Latitude    float64
	Longitude   float64
	Liked       bool
}

func (q *Queries) ListPlaces(ctx context.Context, arg ListPlacesParams) ([]ListPlacesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlaces,
		arg.Limit,
		arg.Offset,
		arg.UserID,
		arg.Lon,
		arg.Lat,
		arg.RadiusMeters,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlacesRow
	for rows.Next() {
		var i ListPlacesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Description,
			&i.Latitude,
			&i.Longitude,
			&i.Liked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
