// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: place.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const addPlaceImagesBatch = `-- name: AddPlaceImagesBatch :exec
INSERT INTO place_image (place_id, url, description, is_primary)
SELECT
    unnest($1::uuid[]),
    unnest($2::text[]),
    unnest($3::text[]),
    unnest($4::boolean[])
`

type AddPlaceImagesBatchParams struct {
	PlaceIds     []uuid.UUID
	Urls         []string
	Descriptions []string
	IsPrimaries  []bool
}

func (q *Queries) AddPlaceImagesBatch(ctx context.Context, arg AddPlaceImagesBatchParams) error {
	_, err := q.db.ExecContext(ctx, addPlaceImagesBatch,
		pq.Array(arg.PlaceIds),
		pq.Array(arg.Urls),
		pq.Array(arg.Descriptions),
		pq.Array(arg.IsPrimaries),
	)
	return err
}

const createPlacesBatch = `-- name: CreatePlacesBatch :many
INSERT INTO place (name, description, category, location)
SELECT
    unnest($1::text[]),
    unnest($2::text[]),
    unnest($3::text[]),
    ST_SetSRID(ST_MakePoint(unnest($4::float8[]), unnest($5::float8[])), 4326)
RETURNING id
`

type CreatePlacesBatchParams struct {
	Names        []string
	Descriptions []string
	Categories   []string
	Longs        []float64
	Lats         []float64
}

func (q *Queries) CreatePlacesBatch(ctx context.Context, arg CreatePlacesBatchParams) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, createPlacesBatch,
		pq.Array(arg.Names),
		pq.Array(arg.Descriptions),
		pq.Array(arg.Categories),
		pq.Array(arg.Longs),
		pq.Array(arg.Lats),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaces = `-- name: ListPlaces :many
SELECT
    p.id,
    p.name,
    p.category,
    p.description,
    ST_AsGeoJSON(p.location)::json AS geojson,
    COALESCE(
        json_agg(
            json_build_object(
                'url', i.url,
                'description', i.description,
                'is_primary', i.is_primary
            )
        ) FILTER (WHERE i.id IS NOT NULL),
        '[]'
    )::json AS images
FROM place p
LEFT JOIN place_image i ON p.id = i.place_id
WHERE ST_DWithin(
    p.location,
    ST_SetSRID(ST_MakePoint($3::float, $4::float), 4326),
    $5::float
)
GROUP BY p.id
ORDER BY p.id
LIMIT $1 OFFSET $2
`

type ListPlacesParams struct {
	Limit        int32
	Offset       int32
	Lon          float64
	Lat          float64
	RadiusMeters float64
}

type ListPlacesRow struct {
	ID          uuid.UUID
	Name        string
	Category    string
	Description sql.NullString
	Geojson     json.RawMessage
	Images      json.RawMessage
}

func (q *Queries) ListPlaces(ctx context.Context, arg ListPlacesParams) ([]ListPlacesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlaces,
		arg.Limit,
		arg.Offset,
		arg.Lon,
		arg.Lat,
		arg.RadiusMeters,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlacesRow
	for rows.Next() {
		var i ListPlacesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Description,
			&i.Geojson,
			&i.Images,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
