// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: places.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createPlace = `-- name: CreatePlace :one

INSERT INTO places (name, description, category, location)
VALUES (
    $1,
    $2,
    $3,
    ST_SetSRID(ST_MakePoint($4::float, $5::float), 4326) -- Convert Lat/Lon to Geometry
)
RETURNING id, name, category, created_at
`

type CreatePlaceParams struct {
	Name        string
	Description sql.NullString
	Category    string
	Column4     float64
	Column5     float64
}

type CreatePlaceRow struct {
	ID        uuid.UUID
	Name      string
	Category  string
	CreatedAt time.Time
}

// internal/database/queries/places.sql
func (q *Queries) CreatePlace(ctx context.Context, arg CreatePlaceParams) (CreatePlaceRow, error) {
	row := q.db.QueryRowContext(ctx, createPlace,
		arg.Name,
		arg.Description,
		arg.Category,
		arg.Column4,
		arg.Column5,
	)
	var i CreatePlaceRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}

const getNearbyPlaces = `-- name: GetNearbyPlaces :many
SELECT
    id,
    name,
    category,
    description,
    ST_AsGeoJSON(location)::json AS geojson -- Return standard JSON directly!
FROM places
WHERE ST_DWithin(
    location,
    ST_SetSRID(ST_MakePoint($1::float, $2::float), 4326),
    $3::float
)
LIMIT 50
`

type GetNearbyPlacesParams struct {
	Lon          float64
	Lat          float64
	RadiusMeters float64
}

type GetNearbyPlacesRow struct {
	ID          uuid.UUID
	Name        string
	Category    string
	Description sql.NullString
	Geojson     json.RawMessage
}

func (q *Queries) GetNearbyPlaces(ctx context.Context, arg GetNearbyPlacesParams) ([]GetNearbyPlacesRow, error) {
	rows, err := q.db.QueryContext(ctx, getNearbyPlaces, arg.Lon, arg.Lat, arg.RadiusMeters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNearbyPlacesRow
	for rows.Next() {
		var i GetNearbyPlacesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Description,
			&i.Geojson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
