// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: place.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const addPlaceImagesBatch = `-- name: AddPlaceImagesBatch :exec
INSERT INTO place_image (place_id, url, description, is_primary)
SELECT
    unnest($1::uuid[]),
    unnest($2::text[]),
    unnest($3::text[]),
    unnest($4::boolean[])
`

type AddPlaceImagesBatchParams struct {
	PlaceIds     []uuid.UUID
	Urls         []string
	Descriptions []string
	IsPrimaries  []bool
}

func (q *Queries) AddPlaceImagesBatch(ctx context.Context, arg AddPlaceImagesBatchParams) error {
	_, err := q.db.ExecContext(ctx, addPlaceImagesBatch,
		pq.Array(arg.PlaceIds),
		pq.Array(arg.Urls),
		pq.Array(arg.Descriptions),
		pq.Array(arg.IsPrimaries),
	)
	return err
}

const createPlacesBatch = `-- name: CreatePlacesBatch :many
INSERT INTO place (name, description, category, location, tags, opening_hours)
SELECT
    unnest($1::text[]),
    unnest($2::text[]),
    unnest($3::text[]),
    ST_SetSRID(ST_MakePoint(unnest($4::float8[]), unnest($5::float8[])), 4326),
    unnest(COALESCE($6::text[], ARRAY[]::text[]))::jsonb,
    unnest(COALESCE($7::text[], ARRAY[]::text[]))
RETURNING id
`

type CreatePlacesBatchParams struct {
	Names            []string
	Descriptions     []string
	Categories       []string
	Longs            []float64
	Lats             []float64
	Tags             []string
	OpeningHoursList []string
}

func (q *Queries) CreatePlacesBatch(ctx context.Context, arg CreatePlacesBatchParams) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, createPlacesBatch,
		pq.Array(arg.Names),
		pq.Array(arg.Descriptions),
		pq.Array(arg.Categories),
		pq.Array(arg.Longs),
		pq.Array(arg.Lats),
		pq.Array(arg.Tags),
		pq.Array(arg.OpeningHoursList),
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlaceByID = `-- name: GetPlaceByID :one
SELECT
    p.id,
    p.name,
    p.category,
    p.description,
    ST_Y(p.location::geometry)::float AS latitude,
    ST_X(p.location::geometry)::float AS longitude,
    COALESCE(upi.liked, FALSE) AS liked,
    COALESCE(p.tags, '[]'::jsonb) AS tags,
    p.opening_hours,
    (SELECT COUNT(*)::int FROM user_place_interactions WHERE place_id = p.id AND liked = true) AS like_count,
    (SELECT COUNT(*)::int FROM collection_place WHERE place_id = p.id) AS save_count,
    (SELECT COUNT(*)::int FROM user_place_interactions WHERE place_id = p.id AND hidden = true) AS hide_count
FROM place p
LEFT JOIN user_place_interactions upi ON p.id = upi.place_id AND upi.user_id = $1::uuid
WHERE p.id = $2::uuid
`

type GetPlaceByIDParams struct {
	UserID  uuid.UUID
	PlaceID uuid.UUID
}

type GetPlaceByIDRow struct {
	ID           uuid.UUID
	Name         string
	Category     string
	Description  sql.NullString
	Latitude     float64
	Longitude    float64
	Liked        bool
	Tags         pqtype.NullRawMessage
	OpeningHours sql.NullString
	LikeCount    int32
	SaveCount    int32
	HideCount    int32
}

func (q *Queries) GetPlaceByID(ctx context.Context, arg GetPlaceByIDParams) (GetPlaceByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPlaceByID, arg.UserID, arg.PlaceID)
	var i GetPlaceByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.Description,
		&i.Latitude,
		&i.Longitude,
		&i.Liked,
		&i.Tags,
		&i.OpeningHours,
		&i.LikeCount,
		&i.SaveCount,
		&i.HideCount,
	)
	return i, err
}

const listNearbyPlaces = `-- name: ListNearbyPlaces :many
SELECT
    p.id,
    p.name,
    p.category,
    p.description,
    ST_Y(p.location::geometry)::float AS latitude,
    ST_X(p.location::geometry)::float AS longitude,
    COALESCE(upi.liked, FALSE) AS liked,
    COALESCE(p.tags, '[]'::jsonb) AS tags,
    p.opening_hours,
    (SELECT COUNT(*)::int FROM user_place_interactions WHERE place_id = p.id AND liked = true) AS like_count,
    (SELECT COUNT(*)::int FROM collection_place WHERE place_id = p.id) AS save_count,
    (SELECT COUNT(*)::int FROM user_place_interactions WHERE place_id = p.id AND hidden = true) AS hide_count
FROM place p
LEFT JOIN user_place_interactions upi ON p.id = upi.place_id AND upi.user_id = $1::uuid
WHERE ST_DWithin(
    p.location::geography,
    ST_SetSRID(ST_MakePoint($2::float, $3::float), 4326)::geography,
    $4::float
) AND COALESCE(upi.hidden, FALSE) = FALSE
ORDER BY ST_Distance(
    p.location::geography,
    ST_SetSRID(ST_MakePoint($2::float, $3::float), 4326)::geography
) ASC
`

type ListNearbyPlacesParams struct {
	UserID       uuid.UUID
	Lon          float64
	Lat          float64
	RadiusMeters float64
}

type ListNearbyPlacesRow struct {
	ID           uuid.UUID
	Name         string
	Category     string
	Description  sql.NullString
	Latitude     float64
	Longitude    float64
	Liked        bool
	Tags         pqtype.NullRawMessage
	OpeningHours sql.NullString
	LikeCount    int32
	SaveCount    int32
	HideCount    int32
}

func (q *Queries) ListNearbyPlaces(ctx context.Context, arg ListNearbyPlacesParams) ([]ListNearbyPlacesRow, error) {
	rows, err := q.db.QueryContext(ctx, listNearbyPlaces,
		arg.UserID,
		arg.Lon,
		arg.Lat,
		arg.RadiusMeters,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNearbyPlacesRow
	for rows.Next() {
		var i ListNearbyPlacesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Description,
			&i.Latitude,
			&i.Longitude,
			&i.Liked,
			&i.Tags,
			&i.OpeningHours,
			&i.LikeCount,
			&i.SaveCount,
			&i.HideCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaceImagesByPlaceIDs = `-- name: ListPlaceImagesByPlaceIDs :many
SELECT place_id, url, description, is_primary
FROM place_image
WHERE place_id = ANY($1::uuid[])
ORDER BY place_id, is_primary DESC
`

type ListPlaceImagesByPlaceIDsRow struct {
	PlaceID     uuid.UUID
	Url         string
	Description sql.NullString
	IsPrimary   sql.NullBool
}

func (q *Queries) ListPlaceImagesByPlaceIDs(ctx context.Context, placeIds []uuid.UUID) ([]ListPlaceImagesByPlaceIDsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlaceImagesByPlaceIDs, pq.Array(placeIds))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlaceImagesByPlaceIDsRow
	for rows.Next() {
		var i ListPlaceImagesByPlaceIDsRow
		if err := rows.Scan(
			&i.PlaceID,
			&i.Url,
			&i.Description,
			&i.IsPrimary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlacesByCategory = `-- name: ListPlacesByCategory :many
SELECT
    p.id,
    p.name,
    p.category,
    p.description,
    ST_Y(p.location::geometry)::float AS latitude,
    ST_X(p.location::geometry)::float AS longitude,
    COALESCE(upi.liked, FALSE) AS liked,
    COALESCE(p.tags, '[]'::jsonb) AS tags,
    p.opening_hours,
    (SELECT COUNT(*)::int FROM user_place_interactions WHERE place_id = p.id AND liked = true) AS like_count,
    (SELECT COUNT(*)::int FROM collection_place WHERE place_id = p.id) AS save_count,
    (SELECT COUNT(*)::int FROM user_place_interactions WHERE place_id = p.id AND hidden = true) AS hide_count
FROM place p
LEFT JOIN user_place_interactions upi ON p.id = upi.place_id AND upi.user_id = $1::uuid
WHERE ST_DWithin(
    p.location::geography,
    ST_SetSRID(ST_MakePoint($2::float, $3::float), 4326)::geography,
    $4::float
) AND COALESCE(upi.hidden, FALSE) = FALSE
AND p.category = $5
ORDER BY ST_Distance(
    p.location::geography,
    ST_SetSRID(ST_MakePoint($2::float, $3::float), 4326)::geography
) ASC
`

type ListPlacesByCategoryParams struct {
	UserID       uuid.UUID
	Lon          float64
	Lat          float64
	RadiusMeters float64
	Category     string
}

type ListPlacesByCategoryRow struct {
	ID           uuid.UUID
	Name         string
	Category     string
	Description  sql.NullString
	Latitude     float64
	Longitude    float64
	Liked        bool
	Tags         pqtype.NullRawMessage
	OpeningHours sql.NullString
	LikeCount    int32
	SaveCount    int32
	HideCount    int32
}

func (q *Queries) ListPlacesByCategory(ctx context.Context, arg ListPlacesByCategoryParams) ([]ListPlacesByCategoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlacesByCategory,
		arg.UserID,
		arg.Lon,
		arg.Lat,
		arg.RadiusMeters,
		arg.Category,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlacesByCategoryRow
	for rows.Next() {
		var i ListPlacesByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.Description,
			&i.Latitude,
			&i.Longitude,
			&i.Liked,
			&i.Tags,
			&i.OpeningHours,
			&i.LikeCount,
			&i.SaveCount,
			&i.HideCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
