// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: searched_location.sql

package database

import (
	"context"
)

const isAreaScanned = `-- name: IsAreaScanned :one
SELECT EXISTS (
    SELECT 1 FROM searched_locations
    WHERE lat BETWEEN $1 - 0.01 AND $1 + 0.01
    AND long BETWEEN $2 - 0.01 AND $2 + 0.01
)
`

type IsAreaScannedParams struct {
	Column1 interface{}
	Column2 interface{}
}

func (q *Queries) IsAreaScanned(ctx context.Context, arg IsAreaScannedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isAreaScanned, arg.Column1, arg.Column2)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const logScan = `-- name: LogScan :exec
INSERT INTO searched_locations (lat, long, radius_km) VALUES ($1, $2, $3)
`

type LogScanParams struct {
	Lat      float64
	Long     float64
	RadiusKm float64
}

func (q *Queries) LogScan(ctx context.Context, arg LogScanParams) error {
	_, err := q.db.ExecContext(ctx, logScan, arg.Lat, arg.Long, arg.RadiusKm)
	return err
}
