// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: searched_location.sql

package database

import (
	"context"
)

const isAreaScanned = `-- name: IsAreaScanned :one
SELECT EXISTS (
    SELECT 1 FROM searched_locations
    WHERE (
        6371 * 2 * ASIN(SQRT(
            POWER(SIN(RADIANS($1 - lat) / 2), 2) +
            COS(RADIANS($1)) * COS(RADIANS(lat)) *
            POWER(SIN(RADIANS($2 - long) / 2), 2)
        ))
    ) <= 2.0
)
`

type IsAreaScannedParams struct {
	Lat  float64
	Long float64
}

func (q *Queries) IsAreaScanned(ctx context.Context, arg IsAreaScannedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isAreaScanned, arg.Lat, arg.Long)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const logScan = `-- name: LogScan :exec
INSERT INTO searched_locations (lat, long, radius_km) VALUES ($1, $2, $3)
`

type LogScanParams struct {
	Lat      float64
	Long     float64
	RadiusKm float64
}

func (q *Queries) LogScan(ctx context.Context, arg LogScanParams) error {
	_, err := q.db.ExecContext(ctx, logScan, arg.Lat, arg.Long, arg.RadiusKm)
	return err
}
