// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_place_interactions.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const upsertUserPlaceInteraction = `-- name: UpsertUserPlaceInteraction :exec
INSERT INTO user_place_interactions (
    user_id,
    place_id,
    rating,
    visited,
    saved,
    times_recommended,
    last_recommended_at,
    last_interaction_at,
    created_at,
    updated_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    0,
    NULL,
    NOW(),
    NOW(),
    NOW()
)
ON CONFLICT (user_id, place_id) DO UPDATE
SET rating = EXCLUDED.rating,
    visited = EXCLUDED.visited,
    saved = EXCLUDED.saved,
    last_interaction_at = NOW(),
    updated_at = NOW()
`

type UpsertUserPlaceInteractionParams struct {
	UserID  uuid.UUID
	PlaceID uuid.UUID
	Rating  int32
	Visited bool
	Saved   bool
}

func (q *Queries) UpsertUserPlaceInteraction(ctx context.Context, arg UpsertUserPlaceInteractionParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserPlaceInteraction,
		arg.UserID,
		arg.PlaceID,
		arg.Rating,
		arg.Visited,
		arg.Saved,
	)
	return err
}
