// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_place_interactions.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const upsertUserPlaceInteraction = `-- name: UpsertUserPlaceInteraction :exec
INSERT INTO user_place_interactions (
    user_id,
    place_id,
    liked,
    hidden,
    last_interaction_at,
    created_at,
    updated_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    NOW(),
    NOW()
)
ON CONFLICT (user_id, place_id) DO UPDATE
SET liked = EXCLUDED.liked,
    hidden = EXCLUDED.hidden,
    last_interaction_at = NOW(),
    updated_at = NOW()
`

type UpsertUserPlaceInteractionParams struct {
	UserID            uuid.UUID
	PlaceID           uuid.UUID
	Liked             bool
	Hidden            bool
	LastInteractionAt sql.NullTime
}

func (q *Queries) UpsertUserPlaceInteraction(ctx context.Context, arg UpsertUserPlaceInteractionParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserPlaceInteraction,
		arg.UserID,
		arg.PlaceID,
		arg.Liked,
		arg.Hidden,
		arg.LastInteractionAt,
	)
	return err
}
