services:
  db:
    image: postgis/postgis:15-3.3
    container_name: orbita_db
    ports:
      - "${DB_PORT}:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - orbita_data:/var/lib/postgresql/data

volumes:
  orbita_data:
