name: Deploy to GCP

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/Orbita
            git reset --hard origin/prod
            git pull origin prod

            # 1. Build the Frontend
            cd web
            npm install
            npm run build
            cd ..

            # 2. Build the Backend Binary
            go build -o bin/orbita cmd/server/main.go

            # 5. STOP the old server (Kill process using port 8080 or name orbita)
            echo "Stopping old server..."
            sudo pkill orbita || true

            # 6. START the new server in the background
            echo "Starting new server..."
            nohup ./bin/orbita > orbita.log 2>&1 &
